name: Teste de Código Python

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Clonar repositório
      uses: actions/checkout@2

    - name: Configurar Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Executar testes
    run: |
      pytest test_codigo.py